# Site settings
title: manojmj's blog
description: "Manoj M J's website"
url: "http://www.manojmj.com"
author:
  name: "Manoj M J"
  url: "http://www.manojmj.com"

# Build settings
baseurl:  # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Custom variables
version: "1.0.1"
